### ISSUE TITLE
Couldn't run this project

### ISSUE THREAD

**Issue by Jignesh1805** [Webtrekk/iOS-SDK-Example-App#1]
Downloading project and run in below error come
ld: warning: Auto-Linking supplied '/Users/romaltandel/Desktop/iOS-SDK-Example-App-master/Tests/WebtrekkOld.framework/WebtrekkOld', framework linker option at /Users/romaltandel/Desktop/iOS-SDK-Example-App-master/Tests/WebtrekkOld.framework/WebtrekkOld is not a dylib
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Webtrekk", referenced from:
      objc-class-ref in AAMigrationTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How to solve this error ?

**Comment by MBing** [comment]
Hi Jignesh,

Check the updated version of this repo. The error should be solved. Make sure to use a fresh project/clean. I updated the Webtrekk Pod, it should take version 4.12.3 and then you can build the project without errors.

Please check and close the issue if it is solved. Thanks!

**Comment by Jignesh1805** [comment]
Thank you MBing
